#!/usr/bin/env bash
# LOCALMEM macOS Desktop Setup
# Installs and configures localmem for local use on macOS.
#
# Usage:
#   chmod +x deploy/setup-macos.sh
#   ./deploy/setup-macos.sh [--no-launchd] [--install-dir DIR]
#
# What it does:
#   1. Finds Python 3.12+ (homebrew or system)
#   2. Creates venv and installs LOCALMEM
#   3. Creates data/log/config directories
#   4. Generates config YAML with device auto-detection
#   5. Copies agent manifests
#   6. Optionally installs launchd plist for auto-start on login

set -euo pipefail

# --- Defaults ---
INSTALL_DIR="$HOME/.local/opt/localmem"
DATA_DIR="$HOME/Library/Application Support/localmem"
LOG_DIR="$HOME/Library/Logs/localmem"
CONFIG_DIR="$HOME/.config/localmem"
INSTALL_LAUNCHD=true
ENABLE_AUTH=false
QDRANT_MODE="local"
QDRANT_URL=""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# --- Parse args ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-launchd)    INSTALL_LAUNCHD=false; shift ;;
        --install-dir)   INSTALL_DIR="$2"; shift 2 ;;
        --data-dir)      DATA_DIR="$2"; shift 2 ;;
        --config-dir)    CONFIG_DIR="$2"; shift 2 ;;
        --auth)          ENABLE_AUTH=true; shift ;;
        --qdrant-server) QDRANT_MODE="server"; QDRANT_URL="$2"; shift 2 ;;
        -h|--help)
            cat <<HELP
Usage: $0 [options]

  --no-launchd            Skip launchd plist install
  --install-dir DIR       Install dir (default: ~/.local/opt/localmem)
  --data-dir DIR          Data dir (default: ~/Library/Application Support/localmem)
  --config-dir DIR        Config dir (default: ~/.config/localmem)
  --auth                  Generate API key, enable dashboard auth
  --qdrant-server URL     Use remote Qdrant at URL (default: local mode)
HELP
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "=== LOCALMEM macOS Setup ==="
echo ""
echo "  Install:  $INSTALL_DIR"
echo "  Data:     $DATA_DIR"
echo "  Config:   $CONFIG_DIR"
echo "  Logs:     $LOG_DIR"
echo "  launchd:  $INSTALL_LAUNCHD"
echo ""

# --- Step 1: Find Python ---
PYTHON=""
for candidate in python3.14 python3.13 python3.12 python3; do
    if command -v "$candidate" &>/dev/null; then
        version=$("$candidate" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+')
        major=$(echo "$version" | cut -d. -f1)
        minor=$(echo "$version" | cut -d. -f2)
        if [[ "$major" -ge 3 && "$minor" -ge 12 ]]; then
            PYTHON="$(command -v "$candidate")"
            echo "[1/7] Python found: $PYTHON ($version)"
            break
        fi
    fi
done

if [[ -z "$PYTHON" ]]; then
    echo "ERROR: Python 3.12+ not found. Install via:"
    echo "  brew install python@3.14"
    echo "  # or: brew install python@3.13"
    exit 1
fi

# --- Step 2: Create venv ---
echo "[2/7] Creating venv at $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
"$PYTHON" -m venv "$INSTALL_DIR/.venv"
source "$INSTALL_DIR/.venv/bin/activate"

# --- Step 3: Install LOCALMEM ---
echo "[3/7] Installing LOCALMEM from source"
pip install --quiet --upgrade pip
pip install --quiet "$PROJECT_DIR"

# --- Step 4: Create directories ---
echo "[4/7] Creating directories"
mkdir -p "$DATA_DIR/qdrant"
mkdir -p "$DATA_DIR/manifests"
mkdir -p "$LOG_DIR"
mkdir -p "$CONFIG_DIR"

# --- Step 5a: Generate API key + prune.env if --auth ---
if [[ "$ENABLE_AUTH" == true ]]; then
    if [[ ! -f "$CONFIG_DIR/prune.env" ]]; then
        API_KEY=$(head -c 24 /dev/urandom | xxd -p -c 256)
        umask 0177
        cat > "$CONFIG_DIR/prune.env" <<ENV
# Generated by setup-macos.sh — sourced by launchd plist and interpolated
# into localmem.yaml via \${LOCALMEM_API_KEY} substitution.
LOCALMEM_API_KEY=$API_KEY
ENV
        chmod 0600 "$CONFIG_DIR/prune.env"
        echo "  API key written to $CONFIG_DIR/prune.env (mode 0600)"
    fi
fi

# --- Step 5: Generate config ---
echo "[5/7] Generating config"
cat > "$CONFIG_DIR/localmem.yaml" << YAML
server:
  host: "localhost"
  port: 8781
  transport: "sse"

storage:
  base_path: "$DATA_DIR"
  qdrant_mode: "$QDRANT_MODE"
  qdrant_path: "$DATA_DIR/qdrant"
  qdrant_url: "$QDRANT_URL"
  sqlite_path: "$DATA_DIR/localmem.db"
  graph_path: "$DATA_DIR/graph.json"

embedding:
  model: "all-MiniLM-L6-v2"
  sparse_model: "Qdrant/bm25"
  device: "auto"

loading:
  l1_top_k: 15
  l1_max_tokens: 120
  decay_rate_per_day: 0.01

graph:
  persistence_debounce_seconds: 5
  max_community_size: 50

concurrency:
  write_timeout_seconds: 30

logging:
  level: "INFO"
  format: "text"
  file: "$LOG_DIR/localmem.log"
  max_bytes: 10000000
  backup_count: 3

intelligence:
  pattern_min_frequency: 3
  correlation_window_hours: 24
  correlation_min_strength: 0.5
  alert_room: "intelligence-alerts"

dashboard:
  enabled: true
  host: "127.0.0.1"
  port: 8782
  auth_enabled: $ENABLE_AUTH
  api_key: "\${LOCALMEM_API_KEY}"
YAML
chmod 0640 "$CONFIG_DIR/localmem.yaml" 2>/dev/null || true

# --- Step 6: Copy manifests ---
echo "[6/7] Copying manifests"
if [[ -d "$PROJECT_DIR/manifests" ]]; then
    cp "$PROJECT_DIR/manifests/"*.yaml "$DATA_DIR/manifests/" 2>/dev/null || true
fi

# --- Step 7: Install launchd plist ---
if [[ "$INSTALL_LAUNCHD" == true ]]; then
    echo "[7/7] Installing launchd plist"
    PLIST_DIR="$HOME/Library/LaunchAgents"
    mkdir -p "$PLIST_DIR"

    PLIST="$PLIST_DIR/com.localmem.server.plist"
    sed \
        -e "s|__INSTALL_DIR__|$INSTALL_DIR|g" \
        -e "s|__CONFIG_DIR__|$CONFIG_DIR|g" \
        -e "s|__LOG_DIR__|$LOG_DIR|g" \
        -e "s|__DATA_DIR__|$DATA_DIR|g" \
        "$SCRIPT_DIR/com.localmem.server.plist" > "$PLIST"

    echo "  Plist installed: $PLIST"
    echo ""
    echo "  To start now:    launchctl load $PLIST"
    echo "  To stop:         launchctl unload $PLIST"
    echo "  To start manually: $INSTALL_DIR/.venv/bin/localmem-serve $CONFIG_DIR/localmem.yaml"
else
    echo "[7/7] Skipping launchd (--no-launchd)"
    echo ""
    echo "  To start manually: $INSTALL_DIR/.venv/bin/localmem-serve $CONFIG_DIR/localmem.yaml"
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Health check:  $INSTALL_DIR/.venv/bin/localmem -c $CONFIG_DIR/localmem.yaml health"
echo "  Smoke test:    $INSTALL_DIR/.venv/bin/localmem -c $CONFIG_DIR/localmem.yaml smoke"
echo "  Server logs:   $LOG_DIR/localmem.log"
