# LOCALMEM Windows Setup
# PowerShell installer that mirrors setup-ubuntu.sh / setup-macos.sh.
#
# Creates a venv, installs LOCALMEM, generates config, and registers two
# Scheduled Tasks (server and daily prune). No external dependencies — pure
# PowerShell + schtasks. For a real Windows service, wrap with NSSM.
#
# Usage:
#   pwsh -ExecutionPolicy Bypass -File deploy\setup-windows.ps1 [options]
#
#   Options:
#     -InstallDir    Default: $env:LOCALAPPDATA\Localmem
#     -DataDir       Default: $env:LOCALAPPDATA\Localmem\data
#     -ConfigDir     Default: $env:LOCALAPPDATA\Localmem\config
#     -LogDir        Default: $env:LOCALAPPDATA\Localmem\logs
#     -PythonExe     Path to python.exe (auto-detect if omitted)
#     -Auth          Generate API key, enable dashboard auth
#     -QdrantServer  Remote Qdrant URL (e.g. http://qdrant:6333)
#     -NoTasks       Skip Scheduled Task registration
#
# Requires Python 3.12+. Run as the user who will own the install — admin
# is NOT required because tasks register under the current user.

[CmdletBinding()]
param(
    [string]$InstallDir = (Join-Path $env:LOCALAPPDATA "Localmem"),
    [string]$DataDir    = $null,
    [string]$ConfigDir  = $null,
    [string]$LogDir     = $null,
    [string]$PythonExe  = $null,
    [switch]$Auth,
    [string]$QdrantServer = "",
    [switch]$NoTasks
)

$ErrorActionPreference = "Stop"

if (-not $DataDir)   { $DataDir   = Join-Path $InstallDir "data" }
if (-not $ConfigDir) { $ConfigDir = Join-Path $InstallDir "config" }
if (-not $LogDir)    { $LogDir    = Join-Path $InstallDir "logs" }

$ProjectDir = Resolve-Path (Join-Path $PSScriptRoot "..")
$QdrantMode = if ($QdrantServer) { "server" } else { "local" }

Write-Host "=== LOCALMEM Windows Setup ==="
Write-Host "  Install:      $InstallDir"
Write-Host "  Data:         $DataDir"
Write-Host "  Config:       $ConfigDir"
Write-Host "  Logs:         $LogDir"
Write-Host "  Qdrant:       $QdrantMode$(if ($QdrantServer) { " ($QdrantServer)" })"
Write-Host "  Auth:         $($Auth.IsPresent)"
Write-Host "  Tasks:        $(-not $NoTasks)"
Write-Host ""

# --- 1. Find Python ---
function Resolve-Python {
    if ($PythonExe -and (Test-Path $PythonExe)) {
        return (Resolve-Path $PythonExe).Path
    }
    foreach ($candidate in @("python3.14", "python3.13", "python3.12", "python")) {
        $found = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($found) {
            $version = & $found.Path --version 2>&1
            if ($version -match "Python (\d+)\.(\d+)") {
                $major = [int]$Matches[1]; $minor = [int]$Matches[2]
                if ($major -ge 3 -and $minor -ge 12) {
                    Write-Host "[1/6] Python: $($found.Path) ($version)"
                    return $found.Path
                }
            }
        }
    }
    throw "Python 3.12+ not found. Install from python.org or via winget: winget install Python.Python.3.14"
}
$Python = Resolve-Python

# --- 2. Directories ---
Write-Host "[2/6] Creating directories"
New-Item -ItemType Directory -Force -Path $InstallDir, $DataDir, $ConfigDir, $LogDir,
    (Join-Path $DataDir "qdrant"),
    (Join-Path $DataDir "manifests") | Out-Null

# --- 3. venv + install ---
Write-Host "[3/6] Creating venv"
$VenvDir = Join-Path $InstallDir ".venv"
if (-not (Test-Path $VenvDir)) {
    & $Python -m venv $VenvDir
}
$VenvPython = Join-Path $VenvDir "Scripts\python.exe"
$VenvScripts = Join-Path $VenvDir "Scripts"
$ServeExe   = Join-Path $VenvScripts "localmem-serve.exe"
$Localmem  = Join-Path $VenvScripts "localmem.exe"

Write-Host "[4/6] Installing LOCALMEM"
& $VenvPython -m pip install --quiet --upgrade pip
& $VenvPython -m pip install --quiet $ProjectDir.Path

# --- 5. API key (if --Auth) + config ---
$EnvFile = Join-Path $ConfigDir "prune.env"
if ($Auth) {
    if (-not (Test-Path $EnvFile)) {
        $bytes = New-Object byte[] 24
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $apiKey = -join ($bytes | ForEach-Object { $_.ToString("x2") })
        Set-Content -Path $EnvFile -Value @"
# Generated by setup-windows.ps1 — read by Scheduled Tasks and
# interpolated into localmem.yaml via `${LOCALMEM_API_KEY}`.
LOCALMEM_API_KEY=$apiKey
"@ -Encoding UTF8
        # ACL: only the current user
        $acl = Get-Acl $EnvFile
        $acl.SetAccessRuleProtection($true, $false)
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            $env:USERNAME, "FullControl", "Allow"
        )
        $acl.SetAccessRule($rule)
        Set-Acl -Path $EnvFile -AclObject $acl
        Write-Host "  API key written to $EnvFile (current user only)"
    }
}

Write-Host "[5/6] Generating config"
$ConfigPath = Join-Path $ConfigDir "localmem.yaml"
$AuthBool   = if ($Auth) { "true" } else { "false" }
$DataDirYaml   = $DataDir.Replace('\', '/')
$LogDirYaml    = $LogDir.Replace('\', '/')
$QdrantPath    = (Join-Path $DataDir "qdrant").Replace('\', '/')
$SqlitePath    = (Join-Path $DataDir "localmem.db").Replace('\', '/')
$GraphPath     = (Join-Path $DataDir "graph.json").Replace('\', '/')
$LogFile       = (Join-Path $LogDir "localmem.log").Replace('\', '/')

$yaml = @"
server:
  host: "127.0.0.1"
  port: 8781
  transport: "sse"

storage:
  base_path: "$DataDirYaml"
  qdrant_mode: "$QdrantMode"
  qdrant_path: "$QdrantPath"
  qdrant_url: "$QdrantServer"
  sqlite_path: "$SqlitePath"
  graph_path: "$GraphPath"

embedding:
  model: "all-MiniLM-L6-v2"
  sparse_model: "Qdrant/bm25"
  device: "auto"

loading:
  l1_top_k: 15
  l1_max_tokens: 120
  decay_rate_per_day: 0.01

graph:
  persistence_debounce_seconds: 5
  max_community_size: 50

concurrency:
  write_timeout_seconds: 30

logging:
  level: "INFO"
  format: "json"
  file: "$LogFile"
  max_bytes: 10000000
  backup_count: 3

dashboard:
  enabled: true
  host: "127.0.0.1"
  port: 8782
  auth_enabled: $AuthBool
  api_key: "`${LOCALMEM_API_KEY}"
"@
Set-Content -Path $ConfigPath -Value $yaml -Encoding UTF8

# --- 6. Scheduled Tasks ---
if ($NoTasks) {
    Write-Host "[6/6] Skipping Scheduled Tasks (-NoTasks)"
} else {
    Write-Host "[6/6] Registering Scheduled Tasks"

    # Task 1: server at logon
    $serveAction = New-ScheduledTaskAction `
        -Execute "powershell.exe" `
        -Argument "-NoProfile -WindowStyle Hidden -Command `"if (Test-Path '$EnvFile') { Get-Content '$EnvFile' | Where-Object { `$_ -match '^[^#]+=' } | ForEach-Object { `$kv = `$_ -split '=',2; [Environment]::SetEnvironmentVariable(`$kv[0], `$kv[1]) } }; & '$ServeExe' '$ConfigPath'`""
    $serveTrigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $serveSettings = New-ScheduledTaskSettingsSet `
        -StartWhenAvailable `
        -RestartCount 99 -RestartInterval (New-TimeSpan -Minutes 1) `
        -DontStopOnIdleEnd
    Register-ScheduledTask `
        -TaskName "LocalmemServer" `
        -Action $serveAction `
        -Trigger $serveTrigger `
        -Settings $serveSettings `
        -Description "LOCALMEM memory server (MCP over SSE)" `
        -Force | Out-Null

    # Task 2: daily prune
    $authHeader = if ($Auth) { '-H "Authorization: Bearer $env:LOCALMEM_API_KEY"' } else { '' }
    $pruneCmd = @"
if (Test-Path '$EnvFile') { Get-Content '$EnvFile' | Where-Object { `$_ -match '^[^#]+=' } | ForEach-Object { `$kv = `$_ -split '=',2; [Environment]::SetEnvironmentVariable(`$kv[0], `$kv[1]) } };
Invoke-RestMethod -Method Post -Uri 'http://127.0.0.1:8782/api/prune/run' -Headers @{ 'Authorization' = "Bearer `$env:LOCALMEM_API_KEY" };
Invoke-RestMethod -Method Post -Uri 'http://127.0.0.1:8782/api/archive/run' -Headers @{ 'Authorization' = "Bearer `$env:LOCALMEM_API_KEY" };
"@
    $pruneAction = New-ScheduledTaskAction `
        -Execute "powershell.exe" `
        -Argument "-NoProfile -WindowStyle Hidden -Command `"$pruneCmd`""
    $pruneTrigger = New-ScheduledTaskTrigger -Daily -At "04:00"
    Register-ScheduledTask `
        -TaskName "LocalmemPrune" `
        -Action $pruneAction `
        -Trigger $pruneTrigger `
        -Description "LOCALMEM daily retention sweep" `
        -Force | Out-Null

    Write-Host "  LocalmemServer: registered (starts at logon)"
    Write-Host "  LocalmemPrune:  registered (daily 04:00)"
}

Write-Host ""
Write-Host "=== Setup complete ==="
Write-Host ""
Write-Host "LOCALMEM v0.5.0"
Write-Host "  Binary: $ServeExe"
Write-Host "  Config: $ConfigPath"
Write-Host "  Data:   $DataDir"
Write-Host "  Logs:   $LogDir"
if ($Auth) { Write-Host "  Auth:   enabled (key in $EnvFile)" }
Write-Host ""
Write-Host "Start now:    Start-ScheduledTask -TaskName LocalmemServer"
Write-Host "Or manually:  & '$ServeExe' '$ConfigPath'"
Write-Host "Health check: & '$Localmem' -c '$ConfigPath' health"
